In [10]:
%load_ext autoreload
%autoreload 2
from dataset import SELMADataset
import open3d as o3d
import seaborn as sns
import copy
import json
from tqdm import trange
from dataset import SELMADataset, get_dataloader
import numpy as np

data_aug = dict(object_noise=dict(
                   num_try=100,
                   translation_std=[0.25, 0.25, 0.25],
                   rot_range=[-0.15707963267, 0.15707963267]
                   ),
               random_flip_ratio=0.5,
               global_rot_scale_trans=dict(
                   rot_range=[-0.78539816, 0.78539816],
                   scale_ratio_range=[0.95, 1.05],
                   translation_std=[0, 0, 0]
                   ), 
               point_range_filter=[-100.0, -100.0, -1, 100.0, 100.0, 3],
               object_range_filter=[-100.0, -100.0, -1, 100.0, 100.0, 3]             
           )

ds = SELMADataset(root_path="../PointPillars/SELMA/CV/dataset/",
             splits_path="./dataset/ImageSets",
             split="all",
             split_extension="txt",
             augment_data=True,
            #  flip=args.random_flip,
            #  gaussian_blur=args.gaussian_blur,
            #  blur_mul=args.blur_mul,
            #  gaussian_noise=args.gaussian_noise,
            #  noise_mul=args.noise_mul,
            #  color_shift=args.color_shift,
            #  color_jitter=args.color_jitter,
            #  cshift_intensity=args.cshift_intensity,
            #  wshift_intensity=args.wshift_intensity,
            sensors=['lidar', 'bbox'],
            #  weather='clear',
            #  time_of_day='sunset',
            sensor_positions=['T'],
            bbox_location="../PointPillars/SELMA/corrected_bbox/",
            n_min=5,
            lidar_data_aug_config=data_aug
            #  class_set='city19',
            #  return_grayscale=args.input_channels==1)
)

def draw_sample(sample):
    pcs = []
    mesh_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(
                            size=2, origin=[0,0,0])
    pcs.append(mesh_frame)

    palette = sns.color_palette("hsv", n_colors=3)

    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(sample[0]['pts'])
    pcs.append(pcd)
        
    for bbox, label in zip(sample[0]['gt_bboxes_3d'], sample[0]['gt_labels']):

        
        
        bb = o3d.geometry.OrientedBoundingBox(np.array([bbox[0],
                                                        bbox[1],
                                                        bbox[2]]),
                                              o3d.geometry.get_rotation_matrix_from_xyz([0.0,0.0,bbox[6]]),
                                              np.array([bbox[3],
                                                        bbox[4],
                                                        bbox[5]]),
                                                        )
        bb.color = palette[label]
        pcs.append(bb)
    o3d.visualization.draw_geometries(pcs)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [17]:
for i in [0, 5000, 10000, 15000, 20000]:
    sample = ds[i]
    draw_sample(sample)
    print(np.min(sample[0]["pts"], axis=0))
    print(np.max(sample[0]["pts"], axis=0))

[-51.42418403 -92.43957633  -0.24825332]
[72.2942211  98.1960843  19.14382936]
[ -95.11623914 -101.25812857   -2.61394742]
[94.51749192 96.29707444 19.79001069]
[-9.07922513e+01 -1.03729957e+02 -4.73973029e-02]
[ 92.95208005 102.39959335  19.17074768]
[-88.49464953 -90.78095308  -0.50981589]
[41.37200667 71.02386803 14.39039747]
[-8.76562542e+01 -9.20629137e+01  8.46576410e-03]
[92.07870456 91.10661727 17.78773716]
